"""Download the web fonts from Google and self-host them under assets/fonts/.

    python tools/fetch_fonts.py

Why self-host: loading fonts from Google puts two extra third-party origins
(fonts.googleapis.com for the CSS, then fonts.gstatic.com for the files) on the
critical path of every page. Each needs its own DNS lookup, TCP connection and TLS
handshake before any text can paint in the real typeface, and the stylesheet is
render-blocking. Served from our own origin the browser reuses the connection it
already has open for the page, and the files get a one-year immutable cache.

Writes assets/fonts/*.woff2 and splices the @font-face rules into style.css between
the FONTS markers, so the fonts cost no stylesheet request of their own. Everything is
committed; re-run this only to change the families, weights or axis ranges below.

Needs the network but nothing outside the standard library.
"""
import pathlib, re, sys, urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "fonts"

# A modern browser UA, or Google serves the old truetype CSS instead of woff2.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")

# Only the subsets the site's text actually needs. "latin" covers ASCII plus the
# Latin-1 accents (Supélec, Zürich); "latin-ext" covers central-European letters.
# Dropping cyrillic, greek and vietnamese removes faces we would never serve.
SUBSETS = {"latin", "latin-ext"}

# Weights and axis ranges the stylesheet uses: 400/500/600, italic for <em>, and
# Newsreader's optical-size axis between 18 and 40 (see font-variation-settings).
QUERY = ("family=Newsreader:ital,opsz,wght@0,18..40,400;0,18..40,500;0,18..40,600;"
         "1,18..40,400;1,18..40,500"
         "&family=IBM+Plex+Sans:wght@400;500;600"
         "&family=IBM+Plex+Mono:wght@400;500"
         "&display=swap")


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read() if binary else r.read().decode("utf-8")


def main():
    css = get(f"https://fonts.googleapis.com/css2?{QUERY}")
    OUT.mkdir(parents=True, exist_ok=True)

    # The CSS is a run of "/* subset */ @font-face {...}" pairs.
    parts = re.split(r"/\* ([a-z-]+) \*/", css)
    kept, seen, total = [], {}, 0
    for i in range(1, len(parts), 2):
        subset, block = parts[i], parts[i + 1]
        if subset not in SUBSETS:
            continue
        url = re.search(r"url\((https://[^)]+)\)", block)
        fam = re.search(r"font-family: '([^']+)'", block)
        if not (url and fam):
            continue
        src = url.group(1)
        if src not in seen:
            slug = fam.group(1).lower().replace(" ", "-")
            name = f"{slug}-{subset}-{src.rsplit('/', 1)[-1][:8]}.woff2"
            data = get(src, binary=True)
            (OUT / name).write_bytes(data)
            seen[src] = name
            total += len(data)
            print(f"  {len(data):>7,}  {name}")
        kept.append(block.strip().replace(f"url({src})", f"url(assets/fonts/{seen[src]})"))

    # Splice into style.css rather than shipping a second stylesheet: one request, and the
    # @font-face rules arrive with the rules that use them.
    css_path = ROOT / "style.css"
    sheet = css_path.read_text(encoding="utf-8")
    start, end = "/* FONTS:start */", "/* FONTS:end */"
    block = (f"{start}\n"
             "/* Self-hosted, generated by tools/fetch_fonts.py -- do not edit by hand.\n"
             "   Served from our own origin so no third-party DNS, TLS or render-blocking\n"
             "   stylesheet sits in front of the first paint. */\n"
             + "\n".join(kept) + f"\n{end}")
    if start in sheet and end in sheet:
        sheet = re.sub(re.escape(start) + r".*?" + re.escape(end), lambda _: block, sheet, flags=re.S)
    else:
        sheet = block + "\n\n" + sheet
    css_path.write_text(sheet, encoding="utf-8", newline="\n")

    print(f"\n{len(seen)} files, {total:,} bytes -> assets/fonts/")
    print(f"{len(kept)} @font-face rules spliced into style.css")
    # A browser only fetches a face whose unicode-range and style the page actually uses,
    # so an English page pulls the latin files and leaves latin-ext on the shelf.
    latin = sum((OUT / n).stat().st_size for n in seen.values() if "-latin-" in n)
    print(f"of which latin only (what an English page fetches): {latin:,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
